on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: learndeployreg.azurecr.io
        username: ${{ secrets.acr_learndeployreg_username }}
        password: ${{ secrets.acr_learndeployreg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t learndeployreg.azurecr.io/githubtest:${{ github.sha }}
        docker push learndeployreg.azurecr.io/githubtest:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_githubtest_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep githubtest0321 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace githubtest0321`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: githubtest0321
        container-registry-url: learndeployreg.azurecr.io
        container-registry-username: ${{ secrets.acr_learndeployreg_username }}
        container-registry-password: ${{ secrets.acr_learndeployreg_password }}
        secret-name: githubtestdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: githubtest0321
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          learndeployreg.azurecr.io/githubtest:${{ github.sha }}
        imagepullsecrets: |
          githubtestdockerauth